### ISSUE TITLE
Need Assistance to Obtain blockdag-miner Binary for Testnet

### ISSUE THREAD

**Issue by Cupacapi** [BlockdagNetworkLabs/blockdag-scripts#12]
Hello,

I am currently setting up a BlockDAG node on the testnet. I've followed the setup instructions provided in the repository, but I am unable to find the blockdag-miner binary required for mining operations on the testnet.

Could you please provide guidance or a direct link to download the blockdag-miner binary? Any help would be greatly appreciated.

Thank you!

**Comment by dev001101** [comment]
Hi @Cupacapi, To start mining on the testnet, you can use the --generate flag with the BlockDAG node command, which will start the miner. Additionally, include the --miner flag to ensure mining operations are enabled and don’t forget to set the --mining_addr parameter to specify the address for mining rewards.

For further configuration options, you can refer to the Docker Compose file in the blockdag-scripts repository, where all relevant parameters are outlined.

Let us know if you have any further questions, and happy mining!

**Comment by Cupacapi** [comment]
Hi BlockDAG Support Team,

I am currently running a BlockDAG node on the testnet and have encountered a recurring warning in the logs stating: "Side chain depth too large". This warning appears repeatedly, despite the node being operational and actively mining blocks.

Here are some details of my setup:

    Node Version: BlockDAG 1.0.0

    Miner Address: Tk2cErtZmKbE5KfDFVHPh2EKk5jLdXjzTXNHguVP5jX5kxu7SfDTG

    Docker Compose Configuration:

version: '3'

services:
  bdag:
    image: blockdagnetwork/bdag:latest
    container_name: blockdag-testnet-network
    ports:
      - "38131:38131"
      - "8130:8130"
      - "18545:18545"
      - "18546:18546"
      - "18150:18150"
    volumes:
      - ./bin/bdag/data:/bdag/data
      - ./bin/bdag/logs:/bdag/logs
    command: >
      ./bdag
      --testnet
      --rpclisten=0.0.0.0:38131
      --notls
      --rpcuser=test
      --rpcpass=test
      --miner
      --miningaddr=${MINING_ADDRESS}
      --generate
      --walletpass=test
      --evmenv="--http --http.port=18545 --http.addr=0.0.0.0 --http.api=net,web3,eth,bdag --ws --ws.origins=* --ws.port=18546 --http.corsdomain=* --http.vhosts=*"
      --miningstatesync
      --addpeer=/ip4/3.14.177.55/tcp/18150/p2p/16Uiu2HAmKr4kFun2dLwVZwjS3Q8VfkAcqFm4W94RyBYA3dQ4sn3n
   
Despite trying various troubleshooting steps, including connecting more peers and adjusting my network configuration, the warning persists. Additionally, I am currently using a WiFi connection, which I suspect might be contributing to the issue. I plan to switch to a wired connection soon.

Could you please provide guidance on how to resolve this warning? Any insights or recommended configurations would be greatly appreciated.

Thank you for your assistance.

Best regards,
