### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by BroKenWan** [BlockdagNetworkLabs/blockdag-scripts#13]
#!/bin/bash

mining_address=$1

# Get the Docker Compose version
docker_compose_version=$(docker compose version | awk '{print $4}')

# Check the Docker Compose version
if [[ "$docker_compose_version" =~ ^v2 ]]; then
  echo "Docker Compose version 2 detected. Using the new command."
  MINNING_ADDRESS=$mining_address docker compose up -d
else
  echo "Docker Compose version 1 detected. Using the old command."
  MINNING_ADDRESS=$mining_address docker-compose up -d
fi

**Comment by urkishan** [comment]
Fixed https://github.com/BlockdagNetworkLabs/blockdag-scripts/pull/15
