### ISSUE TITLE
Why copy someone else's code? Shameless scammers！

### ISSUE THREAD

**Issue by blocklee** [BlockdagNetworkLabs/blockdag-scripts#18]
You are scammers who steal other people's code to swindle money.
You’ve blatantly stolen from @QitmeerNetwork , taking credit for work you didn’t do and using it to deceive others for financial gain."

https://qitmeer.medium.com/qitmeer-network-solemnly-declares-resist-plagiarism-and-defend-technological-innovation-74b469e2bf70

**Comment by urkishan** [comment]
We haven't made our core code public yet.

**Comment by blocklee** [comment]
> We haven't made our core code public yet.

Is it because the plagiarized code hasn't been revised yet?
