### ISSUE TITLE
Checking wallet balance

### ISSUE THREAD

**Issue by techmemes** [BlockdagNetworkLabs/blockdag-scripts#9]
Could you please provide insight into how to check the wallet balance once the node has been running for a few hours.

**Comment by RumoursGR** [comment]
After using the wallet.sh command, a wallet has been created with a mining address **AND** a private key. Insert the private key into the MetaMask wallet and, given you've already added the BlockDAG testnet network there, you'll be able to check the $BDAG balance. I hope this helps. :)

**Comment by Harmanqureshi** [comment]
Interesting web

**Comment by dev001101** [comment]
Hi @techmemes , To fetch your wallet balance in BlockDAG UTXO, follow these steps:

Navigate to the blockdag-scripts/linux/bin/wallet directory.

First, update your wallet to the current state by running:

```./blockdag-wallet qc updateblock```

This will sync your wallet with the blockchain.

Once your wallet is fully synced, you can check your balance by running:

``` ./blockdag-wallet qc getbalance your_public_wallet_address```

Replace your_public_wallet_address with your actual wallet address, and you should see your balance displayed.

**Comment by DigiAdm01** [comment]
HI @dev001101, 

I followed your advice provided on November 5th using the PK address generated by the BlockDAG script.

Update wallet    ./blockdag-wallet qc updateblock
Check your balance        ./blockdag-wallet qc getbalance Added Public Wallet

The node ran for about a week and when i followed the above guidance, it said my balance is zero.

Any suggestions on checking my balance?

**Comment by AlliTobba** [comment]
On linux, go to /blockdag-scripts/linux$
Type more wallet.txt, copy the last line in the file.  That is your your_public_wallet_address
Navigate to /blockdag-scripts/linux/bin/wallet$
There you can run: 
./blockdag-wallet qc updateblock
 ./blockdag-wallet qc getbalance your_public_wallet_address

**Comment by CaZ00777** [comment]
thank

> On linux, go to /blockdag-scripts/linux$ Type more wallet.txt, copy the last line in the file. That is your your_public_wallet_address Navigate to /blockdag-scripts/linux/bin/wallet$ There you can run: ./blockdag-wallet qc updateblock ./blockdag-wallet qc getbalance your_public_wallet_address

Thank you very much. you made my night

**Comment by CaZ00777** [comment]
Any ideas on why my wallet still says 0? could it be because i havent synced the wallet?
Is there any thing to worry about with the below?

WARN[0000] /home/Name/blockdag-scripts/linux/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion

**Comment by CaZ00777** [comment]
sorry to bother again, once I get here " /blockdag-scripts/linux/bin/wallet" and I add the command "./blockdag-wallet qc updateblock" it runs continuously and does not end am I doing something wrong?  am I supposed to add my wallet address somehow? if so how do I go about it?
Apologies I'm a noob. any help is appreciated

**Comment by CaZ00777** [comment]
> On linux, go to /blockdag-scripts/linux$ Type more wallet.txt, copy the last line in the file. That is your your_public_wallet_address Navigate to /blockdag-scripts/linux/bin/wallet$ There you can run: ./blockdag-wallet qc updateblock ./blockdag-wallet qc getbalance your_public_wallet_address

Any ideas on why my wallet still says 0? could it be because i havent synced the wallet?
Is there any thing to worry about with the below?

WARN[0000] /home/Name/blockdag-scripts/linux/docker-compose.yml: the attribute version is obsolete, it will be ignored, please remove it to avoid potential confusion

sorry to bother again, once I get here " /blockdag-scripts/linux/bin/wallet" and I add the command "./blockdag-wallet qc updateblock" it runs continuously and does not end am I doing something wrong? am I supposed to add my wallet address somehow? if so how do I go about it?
Apologies I'm a noob. any help is appreciated

**Comment by AlliTobba** [comment]
Enter your wallet address here 
https://bdagscan.com/?chain=UTXO

But the UTXO is dead, you can see it on the bdagscan.com website if you press PAST 90 DAYS

It was mentioned in the AMA earlier, we will need to wipe the nodes next week and setup it up again.
Then we can start the new node software on the 28th of March when TestNet is launched.

**Comment by CaZ00777** [comment]
so no need to run the node until the 28th then as mentioned below?
?

also do any of the files in the blockdag folder need to be modified in any way to insure mining into my wallet?


> Enter your wallet address here https://bdagscan.com/?chain=UTXO
> 
> But the UTXO is dead, you can see it on the bdagscan.com website if you press PAST 90 DAYS
> 
> It was mentioned in the AMA earlier, we will need to wipe the nodes next week and setup it up again. Then we can start the new node software on the 28th of March when TestNet is launched.

**Comment by AlliTobba** [comment]
I am just going to wait for the new software release, it will hopefully be before 28th.
Then I am just going to wipe the current node clean and install the new software.
I think they are going to release the new software sometime in the week.

**Comment by CaZ00777** [comment]
any updates yet?

**Comment by CaZ00777** [comment]
hahaha yeah same here. do you think it will be a similar install to docker or a new UI? guess its a waiting game. Have you removed it all from docker? if you see it first send a msg pls...

**Comment by AlliTobba** [comment]
Have you ordered any miners ?

**Comment by CaZ00777** [comment]
I've got the x1 running on 2 phones. Thanks for the update and advice. I appreciate you mate

**Comment by AlliTobba** [comment]
@CaZ00777 there was an update done a few minutes ago

**Comment by CaZ00777** [comment]
@AlliTobba on git hub? I don't see it do you have a link?

**Comment by AlliTobba** [comment]
https://github.com/BlockdagNetworkLabs/blockdag-scripts/compare/0f0dd56cbd459c6f7e222099f1078fa742fd20c1...b03af6f54750fcc8cc0649f63ae1d3fff298d8a1

**Comment by CaZ00777** [comment]
so install from same scripts?

**Comment by AlliTobba** [comment]
yes, if you don´t have installed already ... I am trying to see if I can update mine via docker

**Comment by AlliTobba** [comment]
https://github.com/BlockdagNetworkLabs/blockdag-scripts/releases/tag/v1.0.0

**Comment by AlliTobba** [comment]
@CaZ00777 was your node clean ?

**Comment by CaZ00777** [comment]
@AlliTobba clean but still the old download. Manually changing everything as per update. Any luck your side?

**Comment by AlliTobba** [comment]
it seems to be running now 

sudo docker stop blockdag-testnet-network
sudo docker run blockdagnetwork/bdag:latest ./bdag --cleanup

sudo git pull

sudo nano docker-compose.yml
-> edit the miningaddr -> save

sudo ./restartWithCleanup.sh

**Comment by CaZ00777** [comment]
I think mine is up and running aswell. Anyway to check if it's running primordial? Feel like it's running as it's not downloading any blocks it's just flying through chain segments. Thought?

**Comment by AlliTobba** [comment]
I have the same, just chain segments .... my docker-compose states .... so I am assuming it´s running correct scripts
image: blockdagnetwork/primordial:v1.0.0

**Comment by AlliTobba** [comment]
Mine is up :-)
https://primordial.bdagscan.com/node?chain=EVM

**Comment by AlliTobba** [comment]
@CaZ00777 I believe I see you node online now :-) 👍 💯

**Comment by CaZ00777** [comment]
@AlliTobba how do you do that?
I just got it running. hahaha

**Comment by AlliTobba** [comment]
Click on the link :-)
https://primordial.bdagscan.com/node?chain=EVM

**Comment by CaZ00777** [comment]
which one is yours?
are you able to search your wallet address? mine comes up with an error 404

**Comment by CaZ00777** [comment]
getting any of this?

Failed to submit new block:2fd37e5487985019574ab277ffb2df71fcd8bd477ab0df3368ac7bc82a953302 ,The tips of block is expired:2fd37e5487985019574ab277ffb2df71fcd8bd477ab0df3368ac7bc82a953302 (error:main chain tip is overdue,submit main parent:b90d6559af872d3b51988091bb102eb086e281e565b694575afa3fbd83e11c86 (31585), but main tip is :38733082f9061c2ec9cbdd05c800889340fbcc9d6024d113aa4b012637eb47a4 (31587). Obsolete depth:2

**Comment by CaZ00777** [comment]
nice I'll have a look

**Comment by AlliTobba** [comment]
yes, I am getting that error as well

**Comment by CaZ00777** [comment]
How has your nodes gone overnight mine seem to be doing ok. How are you checking your balance for your nide wallet? The ./blockdag-wallet qc updateblock doesn't seem to work. @AlliTobba

**Comment by CaZ00777** [comment]
How has your nodes gone overnight mine seem to be doing ok. How are you checking your balance for your nide wallet? The ./blockdag-wallet qc updateblock doesn't seem to work. @AlliTobb

**Comment by AlliTobba** [comment]
@CaZ00777 still the same, Failed to submit new block
I am going to open a new issue

**Comment by CaZ00777** [comment]
Link me too pls

**Comment by AlliTobba** [comment]
It´s this one ..... :-)
https://github.com/BlockdagNetworkLabs/blockdag-scripts/issues/36

**Comment by CaZ00777** [comment]
hey @AlliTobba are you still getting the errors? failed  to submit block?
